name: CI

on: push

jobs:
  build:
    name: apriltag_ros
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3

    - uses: ros-tooling/setup-ros@v0.4

    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: apriltag_ros
        target-ros2-distro: humble
        vcs-repo-file-url: .github/deps.repos
